# Default application configuration that all configurations inherit from.
scss_files: "src/scss/**/*.scss"

# Default severity of all linters.
severity: warning

linters:
  StringQuotes:
    enabled: true
    style: single_quotes
    exclude:
      - src/scss/_variables.scss
