# THIS FILE IS GENERATED AUTOMATICALLY VIA THE `docs-config` GULP TASK. DO NOT OVERRIDE VARIABLES HERE; MODIFY package.json INSTEAD.

name: ucf-athena-framework
version: 1.0.0-beta.8
author:
  name: UCF Web Communications
  email: webcom@ucf.edu
  url: 'https://github.com/UCF'
description: A front-end web framework for UCF websites and applications
homepage: 'https://ucf.github.io/Athena-Framework'
private: false
repository:
  type: git
  url: UCF/Athena-Framework
license: MIT
files:
  - dist
  - src
devDependencies:
  Stickyfill: 'github:wilddeer/stickyfill'
  anchor-js: ^4.1.0
  babel-core: ^6.26.0
  babel-eslint: ^8.0.2
  babel-plugin-transform-es2015-modules-strip: ^0.1.1
  babel-preset-env: ^1.6.1
  bootstrap: 4.0.0-alpha.6
  browser-sync: ^2.18.13
  clipboard: ^1.7.1
  eslint: ^4.11.0
  fs: 0.0.1-security
  gulp: ~3.9.1
  gulp-autoprefixer: ^4.0.0
  gulp-babel: ^7.0.0
  gulp-clean-css: ^3.9.0
  gulp-eslint: ^4.0.0
  gulp-eslint-if-fixed: ^1.0.0
  gulp-footer: ^1.0.5
  gulp-header: ^1.8.9
  gulp-if: ^2.0.2
  gulp-include: ^2.3.1
  gulp-json-to-yaml: 0.0.2
  gulp-rename: ^1.2.2
  gulp-replace: ^0.6.1
  gulp-sass: ~3.1.0
  gulp-scss-lint: ^0.5.0
  gulp-shell: ^0.6.5
  gulp-sourcemaps: ^2.6.1
  gulp-uglify: ^3.0.0
  gulp-util: ^3.0.8
  holderjs: ^2.9.4
  merge: ^1.2.0
  objectFitPolyfill: ^2.1.0
  path: ^0.12.7
  run-sequence: ^2.2.0
browserslist:
  - last 2 versions
dependencies:
  jquery: '>=3.2.1'
  tether: ^1.4.1
scripts:
  version: gulp default && gulp gh-pages && git add --all
